### ISSUE TITLE
Static annotations in Main.java?

### ISSUE THREAD

**Issue by sarnobat** [pcj/google-options#1]
It's unnecessarily complicated having to create a 2nd class when you just want to do something compact (which a lot of apps start out as). How difficult would it be to support static fields that can be accessed from a main method?

**Comment by pcj** [comment]
Hi @sarnobat as this project attempts to stay true to it's upstream form within the bazel project, it's unlikely to add additional features independent of that.  

Note that you can define your options class as a static inner class (does not have to be it's own file).

**Comment by sarnobat** [comment]
Fair enough, thanks for the quick replies and explanations of the rationales.
