### ISSUE TITLE
Specify default value via assignment instead of annotation?

### ISSUE THREAD

**Issue by sarnobat** [pcj/google-options#2]
It would be more natural for a default value to be set via a regular java assignment at declaration time. Can this be done?

**Comment by pcj** [comment]
Did you try it?  Seems like assigning a default value at declaration and omitting the defaultValue annotation part should work (but likely won't find it's way into the usage message block).

**Comment by sarnobat** [comment]
Actually I didn't. When I saw the other issues I was hesitant to invest time in giving this library a try. But I believe you and it's good to know. Ideally the documentation should say this somewhere but I value minimalism in getting started so probably there's no remaining action item. Feel free to close this.
