### ISSUE TITLE
Make use of "final" keyword for fields (somehow)

### ISSUE THREAD

**Issue by sarnobat** [pcj/google-options#3]
I'm not quite sure how this can be done, but I'd be a lot more willing to use this API if we could mark fields as final, since they shouldn't change once set. I know this is a problem because the java compiler expects an assignment either at declaration time or in a constructor. Is there any way to do this?

**Comment by pcj** [comment]
Thanks for your interest!  No I do not know of a way to do this.  If you are going to be exposing the options class widely throughout your application, I'd recommend implementing a separate class/interface, probably using a builder pattern, and regard the options object as the mutable input for your builder method.
