### ISSUE TITLE
java.lang.NoSuchMethodError for 'com.google.common.reflect.TypeToken.isSupertypeOf'

### ISSUE THREAD

**Issue by Trigon** [pcj/google-options#4]
When I ran this, there is an error:
![image](https://user-images.githubusercontent.com/12734646/34913931-df0f6a98-f8d6-11e7-8aa3-3fa5cdf8445f.png)
And there is problem code in `GenericTypeHelper`:
![image](https://user-images.githubusercontent.com/12734646/34913947-fc75b18c-f8d6-11e7-9ee6-873d4b8350aa.png)

I searched and it said it may be a problem related to guava?
I am not sure about that, thanks

**Comment by Trigon** [comment]
FYI:
My java version is 8 and here is the build.gradle:
[build.zip](https://github.com/pcj/google-options/files/1629140/build.zip)

Thank you very much

**Comment by pcj** [comment]
@Trigon was the fix related to your guava version?  If so, might be good to document that here for future reference.  Thanks.

**Comment by Trigon** [comment]
@pcj Your code is good. The issue is made by another lib I used. That jar contains the package com.google.common.reflect which is part of the Guava and the version of it is very old. I have posted an issue on their GitHub page.

Thank you for your reply.
