### ISSUE TITLE
Sync with upstream?

### ISSUE THREAD

**Issue by bootstraponline** [pcj/google-options#5]
It looks like there's no way to sync with the upstream version of `google-options` in bazel? Ideally bazel itself would consume `google-options` as an artifact. Then the code wouldn't have to be manually copy and pasted into a different github repo.

**Comment by pcj** [comment]
Although there may be some changes in the upstream code, this was in place in-house at google for years prior to it being open-sourced.  As such, I consider it feature complete.  Unless there are significant issues noted there are no plans to keep it in sync.
